[package]
name = "nh-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "nh"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
zeroize.workspace = true
rpassword = "7"
nh-core = { path = "../nh-core" }
nh-routes = { path = "../nh-routes" }
nh-tools = { path = "../nh-tools" }
nh-vault = { path = "../nh-vault" }

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
